name: 'Themis'
description: 'Define rules to prevent PRs from being merged'
branding:
  icon: 'moon'
  color: 'purple'
inputs:
  PROJECT_REGEX:
    description: 'Will only allow PRs that match the given project'
    required: false
  LABEL_REGEX:
    description: 'Will reject PRs that match the given label'
    required: false
  CHANGELOG_REGEX:
      description: 'Will reject PRs that are missing updates to the given files'
      required: false
  ORG_LEVEL:
      description: 'Whether to check projects at an organisational level rather than repo level'
      required: false
      default: false
  DEBUG_MODE:
      description: 'Whether to enable console output'
      required: false
      default: false
  GITHUB_TOKEN:
    description: 'The API token for this Action'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
