name: 'Themis'
description: 'Define rules to prevent PRs from being merged'
branding:
  icon: 'moon'
  color: 'purple'
inputs:
  project-regex:
    description: 'Will only allow PRs that match the given project'
    required: false
  label-regex:
    description: 'Will reject PRs that match the given label'
    required: false
  changelog-regex:
      description: 'Will reject PRs that are missing updates to the given files'
      required: false
  debug-mode:
      description: 'Whether to enable console output'
      required: false
      default: false
  GITHUB_TOKEN:
    description: 'The API token for this Action'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
