name: 'Themis'
description: 'Define rules to prevent PRs from being merged'
branding:
  icon: 'moon'
  color: 'purple'
inputs:
  match-regex:
    description: 'The Regex string to match on'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
  with:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}