on: [pull_request]

name: Main Workflow

jobs:
  pr_match_job:
    runs-on: ubuntu-latest
    name: Projec Check
    steps:
    - name: Check PR is in project
      id: match
      uses: js-egton/themis@v2.10
      with:
        project-regex: ^Project [\d]{2}$
        debug-mode: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  label_match_job:
    runs-on: ubuntu-latest
    name: Label Check
    steps:
    - name: Check PR doesn't have invalid label
      id: match
      uses: js-egton/themis@v2.10
      with:
        label-regex: ^breaking-change$
        debug-mode: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
