on: [pull_request]

name: Main Workflow

jobs:
  changelog_watch_job:
    runs-on: ubuntu-latest
    name: CHANGELOG Check
    steps:
    - name: Check PR has updated CHANGELOG
      id: match
      uses: js-egton/themis@v3.2
      with:
        changelog-watch: true
        debug-mode: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pr_match_job:
    runs-on: ubuntu-latest
    name: Project Check
    steps:
    - name: Check PR is in project
      id: match
      uses: js-egton/themis@v3.2
      with:
        project-regex: ^Project [\d]{2}$
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  label_match_job:
    runs-on: ubuntu-latest
    name: Label Check
    steps:
    - name: Check PR doesn't have invalid label
      id: match
      uses: js-egton/themis@v3.2
      with:
        label-regex: ^breaking-change$
        debug-mode: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
