on: [push]

jobs:
  pr_match_job:
    runs-on: ubuntu-latest
    name: A job to validate PR is in a valid project
    steps:
    - name: Check PR is in project
      id: match
      uses: js-egton/themis@v0.1
      with:
        match-regex: ^/Project [\d]{2}/