on: [pull_request]

jobs:
  pr_match_job:
    runs-on: ubuntu-latest
    name: Project Check
    steps:
    - name: Check PR is in project
      id: match
      uses: js-egton/themis@v0.7
      with:
        match-regex: ^/Project [\d]{2}/