on: [pull_request]

jobs:
  pr_match_job:
    runs-on: ubuntu-latest
    name: Merge Check
    steps:
    - name: Check PR matches merge criteria
      id: match
      uses: js-egton/themis@v2.2
      with:
        # project-regex: ^Project [\d]{2}$
        label-regex: ^breaking-change$
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
