on: [pull_request]

name: Main Workflow

jobs:
  changelog_watch_job:
    runs-on: ubuntu-latest
    name: CHANGELOG Check
    steps:
    - name: Check PR has updated CHANGELOG
      id: match
      uses: js-egton/themis@v3.16.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        CHANGELOG_REGEX: CHANGELOG
        DEBUG_MODE: true
  pr_match_job:
    runs-on: ubuntu-latest
    name: Project Check
    steps:
    - name: Check PR is in project
      id: match
      uses: js-egton/themis@v3.16.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        PROJECT_REGEX: ^In flight$
        DEBUG_MODE: true
  pr_org_match_job:
    runs-on: ubuntu-latest
    name: Project Check
    steps:
    - name: Check PR is in org-level project
      id: match
      uses: js-egton/themis@v3.16.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        PROJECT_REGEX: ^Green Triangle$
        ORG_LEVEL: true
        DEBUG_MODE: true
  label_match_job:
    runs-on: ubuntu-latest
    name: Label Check
    steps:
    - name: Check PR doesn't have invalid label
      id: match
      uses: js-egton/themis@v3.16.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        LABEL_REGEX: ^breaking-change$
        DEBUG_MODE: true
