on: [push]

name: Main Workflow

jobs:
  merge_checks:
    runs-on: ubuntu-latest
    name: Merge Check
    steps:
      - name: Check PR doesn't have invalid label
        id: themis_breaking
        uses: js-egton/themis@v3.16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          LABEL_REGEX: ^breaking-change$
          DEBUG_MODE: true

      - name: Check PR has updated CHANGELOG
        id: themis_release
        uses: js-egton/themis@v3.16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CHANGELOG_REGEX: CHANGELOG
          DEBUG_MODE: true

      - name: Check PR is in project
        id: themis_sprint
        uses: js-egton/themis@v3.16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          PROJECT_REGEX: ^In flight$
          DEBUG_MODE: true

      - name: Check PR is in org project
        id: themis_sprint
        uses: js-egton/themis@v3.16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          PROJECT_REGEX: ^Green Triangle$
          DEBUG_MODE: true
          ORG_LEVEL: true
