on: [pull_request]

name: Main Workflow

jobs:
  pr_match_job:
    runs-on: ubuntu-latest
    name: Merge Check
    steps:
    - name: Check PR matches merge criteria
      id: match
      uses: js-egton/themis@v2.8
      with:
        project-regex: ^Project [\d]{2}$
        label-regex: ^breaking-change$
        debug-mode: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
